import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Nav from "./_componenets/navbar/Nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`font-sans ${inter.variable}`}>
        <main className="flex min-h-screen w-full flex-col items-center justify-center bg-blue-600 px-3 text-white">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
